// Code generated by npxray-schema; DO NOT EDIT.

export type RiskLevel = "low" | "watch" | "high" | "severe";

export type FindingSeverity = "info" | "low" | "medium" | "high" | "critical";

export type FindingCategory = "capability" | "metadata" | "dependency" | "anomaly" | "intelligence" | "provenance";

export type FindingConfidence = "high" | "medium" | "low";

export interface PackageRequest {
  raw: string;
  name: string;
  requested: string;
  normalizedSpec: string;
  commandArgs: string[];
  source: "package" | "npx-command" | "local-tarball" | "local-directory";
}

export interface Maintainer {
  name?: string;
  email?: string;
  createdAt?: string;
  addedAt?: string;
  tfa?: boolean | null;
}

export interface DistSignature {
  keyid?: string;
  sig?: string;
}

export interface ProvenanceInfo {
  present: boolean;
  source?: string;
  verified?: boolean;
}

export interface DistInfo {
  tarball?: string;
  shasum?: string;
  integrity?: string;
  unpackedSize?: number;
  fileCount?: number;
  signatures?: DistSignature[];
  provenance?: ProvenanceInfo | null;
}

export interface Advisory {
  id: string;
  source?: string;
  severity?: string;
  title?: string;
  url?: string;
}

export interface NpxrayMetadata {
  provenanceRequired?: boolean;
}

export interface VersionManifest {
  name: string;
  version: string;
  description?: string;
  license?: string;
  repository?: unknown;
  homepage?: string;
  bugs?: unknown;
  scripts?: Record<string, string>;
  bin?: string | Record<string, string> | null;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  bundledDependencies?: unknown;
  bundleDependencies?: unknown;
  dist?: DistInfo;
  deprecated?: string;
  maintainers?: Maintainer[];
  advisories?: Advisory[];
  npxray?: NpxrayMetadata;
}

export interface PackumentSummary {
  description?: string;
  latest?: string;
  tags: Record<string, string>;
}

export interface Finding {
  id: string;
  severity: FindingSeverity;
  category: FindingCategory;
  confidence: FindingConfidence;
  title: string;
  detail: string;
  evidence?: string;
  files?: string[];
  weight: number;
}

export interface PackageMetrics {
  createdAt?: string;
  versionPublishedAt?: string;
  packageAgeDays?: number;
  versionAgeHours?: number;
  maintainers: number;
  directDependencies: number;
  peerDependencies: number;
  optionalDependencies: number;
  binCount: number;
  lifecycleScriptCount: number;
  tarballBytes?: number;
  unpackedBytes?: number;
  fileCount?: number;
  scannedFiles: number;
  tarballEntries?: number;
  tarballEntriesTruncated?: boolean;
  unpackedBytesTruncated?: boolean;
  transitiveDependencies?: number;
  dependencyTreeTruncated?: boolean;
}

export interface TarballFile {
  path: string;
  size: number;
  mode: string;
  type: "file" | "directory" | "symlink" | "other";
  mimeType?: string;
  preview?: string;
}

export interface DependencyNode {
  id: string;
  name: string;
  requested?: string;
  version?: string;
  depth: number;
  score?: number;
  level?: RiskLevel;
  findings?: string[];
  unresolved?: boolean;
  specType?: string;
  resolvedSource?: string;
  resolutionError?: string;
}

export interface DependencyEdge {
  from: string;
  to: string;
  requested: string;
  scope: string;
  depth: number;
}

export interface DependencyTree {
  root: string;
  maxDepth: number;
  nodes: DependencyNode[];
  edges: DependencyEdge[];
  truncated?: boolean;
}

export interface ShareStat {
  label: string;
  value: string;
}

export interface ShareCardData {
  title: string;
  subtitle: string;
  score: number;
  level: RiskLevel;
  packageName: string;
  packageVersion: string;
  topFindings: string[];
  stats: ShareStat[];
}

export interface ScoreBreakdown {
  capability: number;
  metadata: number;
  dependency: number;
  provenance: number;
  anomaly: number;
  intelligence: number;
  bonus: number;
  total: number;
}

export interface Report {
  request: PackageRequest;
  packageUrl: string;
  registryUrl: string;
  manifest: VersionManifest;
  packumentSummary: PackumentSummary;
  metrics: PackageMetrics;
  findings: Finding[];
  score: number;
  level: RiskLevel;
  riskScore: number;
  riskLevel: RiskLevel;
  scoreBreakdown: ScoreBreakdown;
  recommendation: string;
  files?: TarballFile[];
  scannedFiles: TarballFile[];
  dependencyTree?: DependencyTree | null;
  generatedAt: string;
  engineVersion: string;
  cacheKey: string;
  shareCard: ShareCardData;
}
